-- 1) Role for dbt
CREATE OR REPLACE ROLE CARE_GUARANTEE_ROLE;

-- 2) Warehouse for transformations
CREATE OR REPLACE WAREHOUSE TRANSFORM_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 3) Database + schemas
CREATE OR REPLACE DATABASE CARE_GUARANTEE_WATCH;

CREATE OR REPLACE SCHEMA CARE_GUARANTEE_WATCH.RAW_DATA;
CREATE OR REPLACE SCHEMA CARE_GUARANTEE_WATCH.STG;
CREATE OR REPLACE SCHEMA CARE_GUARANTEE_WATCH.REF;
CREATE OR REPLACE SCHEMA CARE_GUARANTEE_WATCH.MART;

-- Role can use the warehouse
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE CARE_GUARANTEE_ROLE;

-- Role can use the database
GRANT USAGE ON DATABASE CARE_GUARANTEE_WATCH TO ROLE CARE_GUARANTEE_ROLE;

-- Role can work in schemas
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
ON ALL SCHEMAS IN DATABASE CARE_GUARANTEE_WATCH
TO ROLE CARE_GUARANTEE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
ON FUTURE SCHEMAS IN DATABASE CARE_GUARANTEE_WATCH
TO ROLE CARE_GUARANTEE_ROLE;


GRANT ROLE CARE_GUARANTEE_ROLE TO USER CARE_GUARANTEE_DBT;
GRANT ROLE CARE_GUARANTEE_ROLE TO USER ALDA1;

GRANT ALL PRIVILEGES
ON DATABASE CARE_GUARANTEE_WATCH
TO ROLE CARE_GUARANTEE_ROLE;

CREATE OR REPLACE STAGE CARE_GUARANTEE_WATCH.RAW_DATA.RAW_STAGE;

CREATE OR REPLACE TABLE CARE_GUARANTEE_WATCH.RAW_DATA.SCB_POPULATION_RAW (
  PAYLOAD VARIANT
);

CREATE OR REPLACE TABLE CARE_GUARANTEE_WATCH.RAW_DATA.GEO_LAN_REGIONS_RAW (
  PAYLOAD VARIANT
);

COPY INTO CARE_GUARANTEE_WATCH.RAW_DATA.SCB_POPULATION_RAW
  (PAYLOAD)
FROM @CARE_GUARANTEE_WATCH.RAW_DATA.RAW_STAGE
FILE_FORMAT = (
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
)
PATTERN = '.*scb_population.*';

COPY INTO CARE_GUARANTEE_WATCH.RAW_DATA.GEO_LAN_REGIONS_RAW
  (PAYLOAD)
FROM @CARE_GUARANTEE_WATCH.RAW_DATA.RAW_STAGE
FILE_FORMAT = (
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
)
PATTERN = '.*lan_regions_simplified.*';

-- Make sure the role can see the DB & schema
GRANT USAGE ON DATABASE CARE_GUARANTEE_WATCH
  TO ROLE CARE_GUARANTEE_ROLE;

GRANT USAGE ON SCHEMA CARE_GUARANTEE_WATCH.RAW_DATA
  TO ROLE CARE_GUARANTEE_ROLE;

-- Allow reading existing tables in RAW_DATA
GRANT SELECT ON ALL TABLES IN SCHEMA CARE_GUARANTEE_WATCH.RAW_DATA
  TO ROLE CARE_GUARANTEE_ROLE;

-- And any tables created there in the future
GRANT SELECT ON FUTURE TABLES IN SCHEMA CARE_GUARANTEE_WATCH.RAW_DATA
  TO ROLE CARE_GUARANTEE_ROLE;

  GRANT USAGE ON SCHEMA CARE_GUARANTEE_WATCH.STG TO ROLE CARE_GUARANTEE_ROLE;
GRANT USAGE ON SCHEMA CARE_GUARANTEE_WATCH.REF TO ROLE CARE_GUARANTEE_ROLE;
GRANT USAGE ON SCHEMA CARE_GUARANTEE_WATCH.MART TO ROLE CARE_GUARANTEE_ROLE;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CARE_GUARANTEE_WATCH.STG TO ROLE CARE_GUARANTEE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CARE_GUARANTEE_WATCH.REF TO ROLE CARE_GUARANTEE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CARE_GUARANTEE_WATCH.MART TO ROLE CARE_GUARANTEE_ROLE;

CREATE OR REPLACE SCHEMA CARE_GUARANTEE_WATCH.REF_SEEDS;

GRANT USAGE ON SCHEMA CARE_GUARANTEE_WATCH.REF_SEEDS
  TO ROLE CARE_GUARANTEE_ROLE;

GRANT CREATE TABLE, CREATE VIEW, SELECT, INSERT, UPDATE, DELETE
  ON SCHEMA CARE_GUARANTEE_WATCH.REF_SEEDS
  TO ROLE CARE_GUARANTEE_ROLE;
