
name: care_guarantee_watch
version: 1.0.0
profile: care_guarantee_watch
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  care_guarantee_watch:
    +materialized: view
    stg:
      +schema: STG
      +materialized: view
    ref:
      +schema: REF
      +materialized: table
    mart:
      +schema: MART
      +materialized: table

seeds:
  +quote_columns: false
  care_guarantee_watch:
    dim_indicator_taxonomy:
      +schema: ref_seeds


on-run-start:
  - "create schema if not exists {{ target.database }}.STG"
  - "create schema if not exists {{ target.database }}.REF"
  - "create schema if not exists {{ target.database }}.MART"
